#+OPTIONS: H:3 
#+OPTIONS: tex:dvipng
#+OPTIONS: toc:nil 
#+STARTUP: align oddeven lognotestate
#+SEQ_TODO: TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n) export(e)
#+Date:  
#+TITLE: Hw2: More practice
#+AUTHOR: Evan Misshula\\ \texttt{Criminal Justice, CUNY Graduate Center}
#+LANGUAGE:   en
#+EXCLUDE_TAGS: noexport


#+LATEX_HEADER: \usepackage{attrib}
#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \let\iint\undefined 
#+LATEX_HEADER: \let\iiint\undefined 
#+LATEX_HEADER: \usepackage{dsfont}
#+LATEX_HEADER: \usepackage[autostyle]{csquotes}
#+LATEX_HEADER: \usepackage[backend=biber,style=authoryear-icomp,sortlocale=de_DE,natbib=true,url=false, doi=true,eprint=false]{biblatex}
#+LATEX_HEADER: \addbibresource{mybib.bib}
#+LATEX_HEADER: \addbibresource{/Users/emisshula/research/citations/refs.bib} 
#+LATEX_HEADER: \usepackage[retainorgcmds]{IEEEtrantools}
#+LATEX_HEADER: \author{Misshula, Evan\\ \texttt{Criminal Justice, CUNY Graduate Center}}
#+LATEX_HEADER: \title{Demonstration Of Instrumental Variables And Control Function Methods}
# \bibliography{mybib.bib,/Users/emisshula/research/citations/refs.bib} 


Day 10, "Creating Views and Indexes"

Quiz Answers

1. What will happen if a unique index is created on a nonunique field?
Depending on which database you are using, you will receive some type of error and no index at all will be created. The constituent fields of a unique index must form a unique value.

2. Are the following statements true or false?

Both views and indexes take up space in the database and therefore must be factored in the planning of the database size.

False. Only indexes take up physical space.
If someone updates a table on which a view has been created, the view must have an identical update performed on it to see the same data.

False. If someone updates a table, then the view will see the updated data.
If you have the disk space and you really want to get your queries smoking, the more indexes the better.

False. Sometimes too many indexes can actually slow down your queries.

3. Is the following CREATE statement correct?

SQL> create view credit_debts as
     (select all from debts
     where account_id = 4);
No. You do not need the parentheses; also the word all should been an *.
4. Is the following CREATE statement correct?

SQL> create unique view debts as
     select * from debts_tbl;
No. There is no such thing as a unique view.
5. Is the following CREATE statement correct?

SQL> drop * from view debts;
No. The correct syntax is
drop view debts;
6. Is the following CREATE statement correct?
SQL> create index id_index on bills
     (account_id);
Yes. This syntax is correct.
Exercise Answers

1. Examine the database system you are using. Does it support views? What options are you allowed to use when creating a view? Write a simple SQL statement that will create a view using the appropriate syntax. Perform some traditional operations such as SELECT or DELETE and then DROP the view.
Check your implementation's data dictionary for the proper tables to query for information on views.

2. Examine the database system you are using to determine how it supports indexes. You will undoubtedly have a wide range of options. Try out some of these options on a table that exists within your database. In particular, determine whether you are allowed to create UNIQUE or CLUSTERED indexes on a table within your database.

Microsoft Access allows developers to use graphical tools to add indexes to a table. These indexes can combine multiple fields, and the sort order can also be set graphically. Other systems require you to type the CREATE INDEX statement at a command line.

3. If possible, locate a table that has several thousand records. Use a stopwatch or clock to time various operations against the database. Add some indexes and see whether you can notice a performance improvement. Try to follow the tips given to you today.

Indexes improve performance when the operation returns a small subset of records. As queries return a larger portion of a table's records, the performance improvement gained by using indexes becomes negligible. Using indexes can even slow down queries in some situations.

Day 11, "Controlling Transactions"

Quiz Answers

1. When nesting transactions, does issuing a ROLLBACK TRANSACTION command cancel the current transaction and roll back the batch of statements into the upper-level transaction? Why or why not?
No. When nesting transactions, any rollback of a transaction cancels all the transactions currently in progress. The effect of all the transactions will not truly be saved until the outer transaction has been committed.

2. Can savepoints be used to "save off" portions of a transaction? Why or why not?
Yes. Savepoints allow the programmer to save off statements within a transaction. If desired, the transaction can then be rolled back to this savepoint instead of to the beginning of the transaction.

3. Can a COMMIT command be used by itself or must it be embedded?
A COMMIT command can be issued by itself or in the transaction.

4. If you issue the COMMIT command and then discover a mistake, can you still use the ROLLBACK command?
Yes and No. You can issue the command, but it will not roll back the changes.

5. Will using a savepoint in the middle of a transaction save all that happened before it automatically?

No. A savepoint comes into play only if a ROLLBACK command is issued--and then only the changes made after the savepoint will be rolled back.

Exercise Answers

1. Use Personal Oracle7 syntax and correct the syntax (if necessary) for the following:
SQL> START TRANSACTION
     INSERT INTO CUSTOMERS VALUES
     ('SMITH', 'JOHN')
SQL> COMMIT;
Answer:

SQL> SET TRANSACTION;
     INSERT INTO CUSTOMERS VALUES
     ('SMITH', 'JOHN');
SQL> COMMIT;
2. Use Personal Oracle7 syntax and correct the syntax (if necessary) for the following:
SQL> SET TRANSACTION;
     UPDATE BALANCES SET CURR_BAL = 25000;
SQL> COMMIT;
Answer:

SQL> SET TRANSACTION;
         UPDATE BALANCES SET CURR_BAL = 25000;
SQL> COMMIT;
This statement is correct and will work quite well; however, you have just updated everyone's current balance to $25,000!
3. Use Personal Oracle7 syntax and correct the syntax (if necessary) for the following:

SQL> SET TRANSACTION;
     INSERT INTO BALANCES VALUES
     ('567.34', '230.00', '8');
SQL> ROLLBACK;
This statement is correct. Nothing will be inserted.
Day 12, "Database Security"

Quiz Answers

1. What is wrong with the following statement?
SQL> GRANT CONNECTION TO DAVID;
There is no CONNECTION role. The proper syntax is
SQL> GRANT CONNECT TO DAVID;
2. True or False (and why): Dropping a user will cause all objects owned by that user to be dropped as well.
This statement is true only if the DROP USER user name CASCADE statement is executed. The CASCADE option tells the system to drop all objects owned by the user as well as that user.

3. What would happen if you created a table and granted select privileges on the table to public?

Everyone could select from your table, even users you may not want to be able to view your data.

4. Is the following SQL statement correct?

SQL> create user RON
     identified by RON;
Yes. This syntax creates a user. However, the user will acquire the default settings, which may not be desirable. Check your implementation for these settings.
5. Is the following SQL statement correct?

SQL> alter RON
     identified by RON;
No. The user is missing. The correct syntax is
SQL> alter user RON
     identified by RON;
6. Is the following SQL statement correct?
SQL> grant connect, resource to RON;
Yes. The syntax is correct.
7. If you own a table, who can select from that table?

Only users with the select privilege on your table.

Exercise Answer

Experiment with your database system's security by creating a table and then by creating a user. Give this user various privileges and then take them away.

(On your own.)

Day 13, "Advanced SQL Topics"

Quiz Answers

1. True or False: Microsoft Visual C++ allows programmers to call the ODBC API directly.
False. Microsoft Visual C++ encapsulates the ODBC library with a set of C++ classes. These classes provide a higher-level interface to the ODBC functions, which results in an easier-to-use set of functions. However, the overall functionality is somewhat limited. If you purchase the ODBC Software Development Kit (SDK) (you can obtain the SDK by joining the Microsoft Developers Network), you can call the API directly from within a Visual C++ application.

2. True or False: The ODBC API can be called directly only from a C program.
False. The ODBC API resides within DLLs that can be bound by a number of languages, including Visual Basic and Borland's Object Pascal.

3. True or False: Dynamic SQL requires the use of a precompiler.
False. Static SQL requires a precomplier. Dynamic SQL is just that: dynamic. The SQL statements used with Dynamic SQL can be prepared and executed at runtime.

4. What does the # in front of a temporary table signify?
SQL Server uses the # to flag a temporary table.

5. What must be done after closing a cursor to return memory?
You must deallocate the cursor. The syntax is

SQL> deallocate cursor cursor_name;
6. Are triggers used with the SELECT statement?
No. They are executed by the use of UPDATE, DELETE, or INSERT.

7. If you have a trigger on a table and the table is dropped, does the trigger still exist?

No. The trigger is automatically dropped when the table is dropped.

Exercise Answers

1. Create a sample database application. (We used a music collection to illustrate these points today.) Break this application into logical data groupings.
2. List of queries you think will be required to complete this application.

3. List the various rules you want to maintain in the database.

4. Create a database schema for the various groups of data you described in step 1.

5. Convert the queries in step 2 to stored procedures.

6. Convert the rules in step 3 to triggers.

7. Combine steps 4, 5, and 6 into a large script file that can be used to build the database and all its associated procedures.

8. Insert some sample data. (This step can also be a part of the script file in step 7.)

9. Execute the procedures you have created to test their functionality.
(On your own.)

Day 14, "Dynamic Uses of SQL"

Quiz Answers

1. In which object does Microsoft Visual C++ place its SQL?
In the CRecordSet object's GetDefaultSQL member. Remember, you can change the string held here to manipulate your table.
2. In which object does Delphi place its SQL?
In the TQuery object.

3. What is ODBC?
ODBC stands for open database connectivity. This technology enables Windows-based programs to access a database through a driver.

4. What does Delphi do?
Delphi provides a scalable interface to various databases.

Exercise Answers

1. Change the sort order in the C++ example from ascending to descending on the State field.
Change the return value of GetDefaultSQL as shown in the following code fragment:

CString CTyssqlSet::GetDefaultSQL()
{
return " SELECT * FROM CUSTOMER ORDER DESC BY STATE ";
}
2. Go out, find an application that needs SQL, and use it.
(On your own.)
Day 15, "Streamlining SQL Statements for Improved Performance"

Quiz Answers

1. What does streamline an SQL statement mean?
Streamlining an SQL statement is taking the path with the least resistance by carefully planning your statement and arranging the elements within your clauses properly.
2. Should tables and their corresponding indexes reside on the same disk?
Absolutely not. If possible, always store tables and indexes separately to avoid disk contention.

3. Why is the arrangement of conditions in an SQL statement important?
For more efficient data access (the path with the least resistance).

4. What happens during a full-table scan?
A table is read row by row instead of using an index that points to specific rows.

5. How can you avoid a full-table scan?
A full-table scan can be avoided by creating an index or rearranging the conditions in an SQL statement that are indexed.

6. What are some common hindrances of general performance?
Common performance pitfalls include

Insufficient shared memory
Limited number of available disk drives
Improper usage of available disk drives
Running large batch loads that are unscheduled
Failing to commit or rollback transactions
Improper sizing of tables and indexes
Exercise Answers

1. Make the following SQL statement more readable.
SELECT EMPLOYEE.LAST_NAME, EMPLOYEE.FIRST_NAME, EMPLOYEE.MIDDLE_NAME,
EMPLOYEE.ADDRESS, EMPLOYEE.PHONE_NUMBER, PAYROLL.SALARY, PAYROLL.POSITION,
EMPLOYEE.SSN, PAYROLL.START_DATE FROM EMPLOYEE, PAYROLL WHERE
EMPLOYEE.SSN = PAYROLL.SSN AND EMPLOYEE.LAST_NAME LIKE 'S%' AND
PAYROLL.SALARY > 20000;
You should reformat the SQL statement as follows, depending on the consistent format of your choice:
SELECT E.LAST_NAME, E.FIRST_NAME, E.MIDDLE_NAME,
       E.ADDRESS, E.PHONE_NUMBER, P.SALARY,
       P.POSITION, E.SSN, P.START_DATE
FROM EMPLOYEE E,
     PAYROLL P
WHERE E.SSN = P.SSN
  AND E.LAST_NAME LIKE 'S%'
  AND P.SALARY > 20000;
2. Rearrange the conditions in the following query to optimize data retrieval time.Use the following statistics (on the tables in their entirety) to determine the order of the conditions:
593 individuals have the last name SMITH.

712 individuals live in INDIANAPOLIS.

3,492 individuals are MALE.

1,233 individuals earn a salary >= 30,000.

5,009 individuals are single.

Individual_id is the primary key for both tables.
SELECT M.INDIVIDUAL_NAME, M.ADDRESS, M.CITY, M.STATE, M.ZIP_CODE,
       S.SEX, S.MARITAL_STATUS, S.SALARY
FROM MAILING_TBL M,
     INDIVIDUAL_STAT_TBL S
WHERE M.NAME LIKE 'SMITH%'
  AND M.CITY = 'INDIANAPOLIS'
  AND S.SEX = 'MALE'
  AND S.SALARY >= 30000
  AND S.MARITAL_STATUS = 'S'
  AND M.INDIVIDUAL_ID = S.INDIVIDUAL_ID;
--------------
Answer:
According to the statistics, your new query should look similar to the following answer. Name like 'SMITH%' is the most restrictive condition because it will return the fewest rows:

SELECT M.INDIVIDUAL_NAME, M.ADDRESS, M.CITY, M.STATE, M.ZIP_CODE,
       S.SEX, S.MARITAL_STATUS, S.SALARY
FROM MAILING_TBL M,
     INDIVIDUAL_STAT_TBL S
WHERE M.INDIVIDUAL_ID = S.INDIVIDUAL_ID
  AND S.MARITAL_STATUS = 'S'
  AND S.SEX = 'MALE'
  AND S.SALARY >= 30000
  AND M.CITY = 'INDIANAPOLIS'
  AND M.NAME LIKE 'SMITH%';
Day 16, "Using Views to Retrieve Useful Information from the Data Dictionary"

Quiz Answers

1. In Oracle, how can you find out what tables and views you own?
By selecting from USER_CATALOG or CAT. The name of the data dictionary object will vary by implementation, but all versions have basically the same information about objects such as tables and views.

2. What types of information are stored in the data dictionary?
Database design, user statistics, processes, objects, growth of objects, performance statistics, stored SQL code, database security.

3. How can you use performance statistics?

Performance statistics suggest ways to improve database performance by modifying database parameters and streamlining SQL, which may also include the use of indexes and an evaluation of their efficiency.

4. What are some database objects?
Tables, indexes, synonyms, clusters, views.

Exercise Answers

Suppose you are managing a small to medium-size database. Your job responsibilities include developing and managing the database. Another individual is inserting large amounts of data into a table and receives an error indicating a lack of space. You must determine the cause of the problem. Does the user's tablespace quota need to be increased, or do you need to allocate more space to the tablespace? Prepare a step-by-step list that explains how you will gather the necessary information from the data dictionary. You do not need to list specific table or view names.

1. Look up the error in your database documentation.
2. Query the data dictionary for information on the table, its current size, tablespace quota on the user, and space allocated in the tablespace (the tablespace that holds the target table).

3. Determine how much space the user needs to finish inserting the data.

4. What is the real problem? Does the user's tablespace quota need to be increased, or do you need to allocate more space to the tablespace?

5. If the user does not have a sufficient quota, then increase the quota. If the current tablespace is filled, you may want to allocate more space or move the target table to a tablespace with more free space.

6. You may decide not to increase the user's quota or not to allocate more space to the tablespace. In either case you may have to consider purging old data or archiving the data off to tape.

These steps are not irrevocable. Your action plan may vary depending upon your company policy or your individual situation.

Day 17, "Using SQL to Generate SQL Statements"

Quiz Answers

1. From which two sources can you generate SQL scripts?
You can generate SQL scripts from database tables and the data dictionary.

2. Will the following SQL statement work? Will the generated output work?

SQL> SET ECHO OFF
SQL> SET FEEDBACK OFF
SQL> SPOOL CNT.SQL
SQL> SELECT 'COUNT(*) FROM  ' || TABLE_NAME || ';'
  2  FROM CAT
  3  /
Yes the SQL statement will generate an SQL script, but the generated script will not work. You need select 'select' in front of count(*):
SELECT 'SELECT COUNT(*) FROM ' || TABLE_NAME || ';'
Otherwise, your output will look like this:
COUNT(*) FROM TABLE_NAME;
which is not a valid SQL statement.
3. Will the following SQL statement work? Will the generated output work?

SQL> SET ECHO OFF
SQL> SET FEEDBACK OFF
SQL> SPOOL GRANT.SQL
SQL> SELECT 'GRANT CONNECT DBA TO ' || USERNAME || ';'
  2  FROM SYS.DBA_USERS
  3  WHERE USERNAME NOT IN ('SYS','SYSTEM','SCOTT')
  4  /
Once again, yes and no. The statement will generate an SQL script, but the SQL that it generates will be incomplete. You need to add a comma between the privileges CONNECT and DBA:
SELECT 'GRANT CONNECT, DBA TO ' || USERNAME || ';'
4. Will the following SQL statement work? Will the generated output work?
SQL> SET ECHO OFF
SQL> SET FEEDBACK OFF
SQL> SELECT 'GRANT CONNECT, DBA TO ' || USERNAME || ';'
  2  FROM SYS.DBA_USERS
  3  WHERE USERNAME NOT IN ('SYS','SYSTEM','SCOTT')
  4  /
Yes. The syntax of the main statement is valid, and the SQL that will be generated will grant CONNECT and DBA to all users selected.
5. True or False: It is best to set feedback on when generating SQL.

False. You do not care how many rows are being selected, as that will not be part of the syntax of your generated statements.

6. True or False: When generating SQL from SQL, always spool to a list or log file for a record of what happened.

False. You should spool to an .sql file, or whatever your naming convention is for an SQL file. However, you may choose to spool within your generated file.

7. True or False: Before generating SQL to truncate tables, you should always make sure you have a good backup of the tables.

True. Just to be safe.

8. What is the ed command?

The ed command takes you into a full screen text editor. ed is very similar to vi on a UNIX system and appears like a Windows Notepad file.

9. What does the spool off command do?
The spool off command closes an open spool file.

Exercise Answers

1. Using the SYS.DBA_USERS view (Personal Oracle7), create an SQL statement that will generate a series of GRANT statements to five new users: John, Kevin, Ryan, Ron, and Chris. Use the column called USERNAME. Grant them Select access to history_tbl.
SQL> SET ECHO OFF
SQL> SET FEEDBACK OFF
SQL> SPOOL GRANTS.SQL
SQL> SELECT 'GRANT SELECT ON HISTORY_TBL TO ' || USERNAME || ';'
  2  FROM SYS.DBA_USERS
  3  WHERE USERNAME IN ('JOHN','KEVIN','RYAN','RON','CHRIS')
  4  /

grant select on history_tbl to JOHN;
grant select on history_tbl to KEVIN;
grant select on history_tbl to RYAN;
grant select on history_tbl to RON;
grant select on history_tbl to CHRIS;
2. Using the examples in this chapter as guidelines, create some SQL statements that will generate SQL that you can use.
There are no wrong answers as long as the syntax is correct in your generated statements.

WARNING: Until you completely understand the concepts presented in this chapter, take caution when generating SQL statements that will modify existing data or database structures.
Day 18, "PL/SQL: An Introduction"

Quiz Answers

1. How is a database trigger used?
A database trigger takes a specified action when data in a specified table is manipulated. For instance, if you make a change to a table, a trigger could insert a row of data into a history table to audit the change.

2. Can related procedures be stored together?
Related procedures may be stored together in a package.

3. True or False: Data Manipulation Language can be used in a PL/SQL statement.
True.

4. True or False: Data Definition Language can be used in a PL/SQL statement.

False. DDL cannot be used in a PL/SQL statement. It is not a good idea to automate the process of making structural changes to a database.

5. Is text output directly a part of the PL/SQL syntax?
Text output is not directly a part of the language of PL/SQL; however, text output is supported by the standard package DBMS_OUTPUT.

6. List the three major parts of a PL/SQL statement.
DECLARE section, PROCEDURE section, EXCEPTION section.

7. List the commands that are associated with cursor control.
DECLARE, OPEN, FETCH, CLOSE.

Exercise Answers

1. Declare a variable called HourlyPay in which the maximum accepted value is 99.99/hour.
DECLARE
     HourlyPay number(4,2);
2. Define a cursor whose content is all the data in the CUSTOMER_TABLE where the CITY is INDIANAPOLIS.
DECLARE
      cursor c1 is
      select * from customer_table
      where city = 'INDIANAPOLIS';
3. Define an exception called UnknownCode.
DECLARE
      UnknownCode EXCEPTION;
4. Write a statement that will set the AMT in the AMOUNT_TABLE to 10 if CODE is A, set the AMT to 20 if CODE is B, and raise an exception called UnknownCode if CODE is neither A nor B. The table has one row.
IF ( CODE = 'A' ) THEN
      update AMOUNT_TABLE
      set AMT = 10;
    ELSIF ( CODE = 'B' ) THEN
       update AMOUNT_TABLE
      set AMT = 20;
    ELSE
      raise UnknownCode;
    END IF; 
Day 19, "Transact-SQL: An Introduction"

Quiz Answers

1. True or False: The use of the word SQL in Oracle's PL/SQL and Microsoft/Sybase's Transact-SQL implies that these products are fully compliant with the ANSI standard.
False. The word is not protected by copyright. The products mentioned do comply with much of the ANSI standard, but they do not fully comply with everything in that standard.

2. True or False: Static SQL is less flexible than Dynamic SQL, although the performance of static SQL can be better.

True. Static SQL requires the use of a precompiler, and its queries cannot be prepared at runtime. Therefore, static SQL is less flexible than dynamic SQL, but because the query is already processed, the performance can be better.

Exercise Answers

1. If you are not using Sybase/Microsoft SQL Server, compare your product's extensions to ANSI SQL to the extensions mentioned today.
Because nearly all of Day 19 deals with Transact-SQL, we did not explore the many other extensions to ANSI SQL. Most documentation that accompanies database products makes some effort to point out any SQL extensions provided. Keep in mind that using these extensions will make porting your queries to other databases more difficult.

2. Write a brief set of statements that will check for the existence of some condition. If this condition is true, perform some operation. Otherwise, perform another operation.

This operation requires an IF statement. There are no wrong answers as long as you follow the syntax for logical statements (IF statements) discussed today.

Day 20, "SQL*Plus"

Quiz Answers

1. Which commands can modify your preferences for an SQL session?
SET commands change the settings available with your SQL session.

2. Can your SQL script prompt a user for a parameter and execute the SQL statement using the entered parameter?

Yes. Your script can accept parameters from a user and pass them into variables.

3. If you are creating a summarized report on entries in a CUSTOMER table, how would you group your data for your report?

You would probably break your groups by customer because you are selecting from the CUSTOMER table.

4. Are there limitations to what you can have in your LOGIN.SQL file?

The only limitations are that the text in your LOGIN.SQL file must be valid SQL and SQL*Plus commands.

5. True or False: The DECODE function is the equivalent of a loop in a procedural programming language.

False. DECODE is like an IF...THEN statement.

6. True or False: If you spool the output of your query to an existing file, your output will be appended to that file.

False. The new output will overwrite the original file.

Exercise Answers

1. Using the PRODUCTS table at the beginning of Day 20, write a query that will select all data and compute a count of the records returned on the report without using the SET FEEDBACK ON command.
compute sum of count(*) on report
    break on report
    select product_id, product_name, unit_cost, count(*)
    from products
    group by product_id, product_name, unit_cost;
2. Suppose today is Monday, May 12, 1998. Write a query that will produce the following output:
Today is Monday, May 12 1998
Answer:

set heading off
select to_char(sysdate,' "Today is "Day, Month dd yyyy')
from dual;
3. Use the following SQL statement for this exercise:
1  select *
2  from orders
3  where customer_id = '001'
4* order by customer_id;
Without retyping the statement in the SQL buffer, change the table in the FROM clause to the CUSTOMER table:

l2
c/orders/customer
Now append DESC to the ORDER BY clause:
l4
append DESC
Day 21, "Common SQL Mistakes/Errors and Resolutions"

Quiz Answers

1. A user calls and says, "I can't sign on to the database. But everything was working fine yesterday. The error says invalid user/password. Can you help me?" What steps should you take?
At first you would think to yourself, yeah sure, you just forgot your password. But this error can be returned if a front-end application cannot connect to the database. However, if you know the database is up and functional, just change the password by using the ALTER USER command and tell the user what the new password is.

2. Why should tables have storage clauses and a tablespace destination?
In order for tables not to take the default settings for storage, you must include the storage clause. Otherwise medium to large tables will fill up and take extents, causing slower performance. They also may run out of space, causing a halt to your work until the DBA can fix the space problem.

Exercise Answers

1. Suppose you are logged on to the database as SYSTEM, and you wish to drop a table called HISTORY in your schema. Your regular user ID is JSMITH. What is the correct syntax to drop this table?

Because you are signed on as SYSTEM, be sure to qualify the table by including the table owner. If you do not specify the table owner, you could accidentally drop a table called HISTORY in the SYSTEM schema, if it exists.
SQL> DROP TABLE JSMITH.HISTORY;
2. Correct the following error:
INPUT:

SQL> select sysdate DATE
  2  from dual;
OUTPUT:

select sysdate DATE
               *
ERROR at line 1:
ORA-00923: FROM keyword not found where expected
DATE is a reserved word in Oracle SQL. If you want to name a column heading DATE, then you must use double quotation marks: "DATE".
